[mypy]
warn_unused_configs = True
allow_redefinition = True
explicit_package_bases = True
check_untyped_defs = True
modules =
    azul.types,
    azul.lib.collections,
    azul.args,
    azul.lib.attrs,
    azul.auth,
    azul.azulclient,
    azul.lib.bytes,
    azul.lib.caching,
    azul.chalice,
    azul.lib.bigquery,
    azul.bigquery_reservation,
    azul.csp,
    azul.deployment,
    azul.lib.strings,
    azul.logging,
    azul,
    azul.docker,
    azul.doctests,
    azul.drs,
    azul.dss,
    azul.lib.enums,
    azul.es,
    azul.lib.exceptions,
    azul.files,
    azul.health,
    azul.hmac,
    azul.http,
    azul.lib.iterators,
    azul.json,
    azul.lib.json_freeze,
    azul.lambda_layer,
    azul.lambdas,
    azul.modules,
    azul.oauth2,
    azul.lib.objects,
    azul.queues,
    azul.template,
    azul.terra,
    azul.terraform,
    azul.lib.threads,
    azul.lib.time,
    azul.uuids,
    azul.plugins,
    azul.service.controller,
    azul.digests,
    lambdas.indexer.app,
    azul.schemas,
    azul_test_case,
    test_tagging,
    scripts.reindex,
    scripts.mirror,
    scripts.post_deploy_tdr,
    scripts.find_in_snapshots,
    scripts.can_bundle,
    scripts.delete_older_function_versions,
    scripts.zenhub_to_github,
    azul.plugins.metadata.anvil.bundle,
    azul.plugins.metadata.anvil.schema,
    azul.plugins.metadata.anvil.indexer.aggregate,
    azul.plugins.metadata.anvil.indexer.transform,
    azul.plugins.metadata.anvil.service.aggregation,
    azul.plugins.metadata.anvil.service.response,
    azul.plugins.metadata.anvil,
    azul.plugins.metadata.hca.bundle,
    azul.plugins.metadata.hca.indexer.aggregate,
    azul.plugins.metadata.hca.indexer.transform,
    azul.plugins.metadata.hca.service.contributor_matrices,
    azul.plugins.metadata.hca.service.aggregation,
    azul.plugins.metadata.hca.service.response,
    azul.plugins.metadata.hca,
    azul.plugins.metadata.anvil.service.filter,
    azul.plugins.metadata.hca.service.filter,
    azul.lib.functions,
    azul.service.storage_service,
    azul.service.source_service,
    azul.service,
    azul.service.source_controller,
    azul.service.query_controller,
    azul.service.index_controller,
    azul.service.catalog_controller,
    azul.service.manifest_controller,
    azul.service.repository_controller,
    azul.service.drs_controller,
    azul.service.manifest_service,


packages =
    azul.indexer,
    azul.openapi

[mypy-furl.*]
follow_untyped_imports = True

[mypy-requests.*]
follow_untyped_imports = True

[mypy-docker.*]
; https://github.com/python/typeshed/issues/13439
follow_untyped_imports = True

[mypy-aws_requests_auth.boto_utils]
follow_untyped_imports = True

