name: 'CI'

on: [push]

jobs:

  test:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 45
    steps:

      - uses: 'actions/checkout@v4'

      - run: 'cat environment.boot >> "$GITHUB_ENV"'

      - uses: 'actions/setup-python@v5'
        with:
          python-version: '${{ env.azul_python_version }}'
          cache: 'pip'
          cache-dependency-path: 'requirements.dev.txt'

      - name: 'Create environment'
        run: |
          source environment | true  # load global defaults
          _select dev | true
          source environment | true
          make virtualenv
          source .venv/bin/activate
          make requirements | true

      - name: 'Run the export script, should bomb due to no credentials, not a dependency issue'
        run: |
          python scripts/export_inspector_findings.py